### ISSUE TITLE
go client doesn't handle rows that span multiple columns

### ISSUE THREAD

**Issue by KevinAnthony** [atye/wikitable2json#85]
An example is this here:
https://en.wikipedia.org/wiki/List_of_Chainsaw_Man_chapters

This returns an error when parsing the 3rd row on line 57 for `pkg/client/format.go`

How would you feel having the option to skip rows that fail to parse and just return valid rows?

**Comment by atye** [comment]
I'm away from my computer for the weekend but I'll take a look as soon I can next week.

**Comment by atye** [comment]
The behavior is that the Wikipedia API returns HTML with an empty row, which does not exist in the real page, which is odd. My API includes this row and it breaks they key/value response since it requires the rows to be equal length.

![image](https://github.com/atye/wikitable2json/assets/5854121/d8a9d36c-41d6-4d8d-960d-e91c5f9cd3d2)

I'm considering a solution to discard row elements that have no child elements.

Regarding skipping rows that fail to parse, I'm not sure I want to have an API that doesn't return all of the data. Either it does, or it errors. For a table that has a row with data and doesn't match the keys length, I'm considering making empty keys for the columns that don't match a key.

**Comment by KevinAnthony** [comment]
I feel like this is caused by columns that span rows.
The best way to handle this, or errors in general might be a error handler callback, where the caller can decide what to do?

**Comment by atye** [comment]
This API can handle row and columns spans but it was a design choice to return an error if any data row doesn't match the length of the keys. I've made a change to not do that but it's not live yet. 

There is another issue with this table because it contains a nested table which confuses the parsing. The parsing doesn't error but the output isn't quite right. Investigating this.

**Comment by atye** [comment]
I pushed changes to branch issue-85. Since you are using the client, could you run `go get github.com/atye/wikitable2json@issue-85` and see if the result is what you expect? I used the code below. The attached file is the data marshaled as json. It looks correct to me. Let me know if it works for you.

```
func main() {
	c := client.NewTableGetter("your-user-agent")

	data, err := c.GetTablesKeyValue(context.Background(), "List_of_Chainsaw_Man_chapters", "en", false, 1)
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(data)
}
```
[json.txt](https://github.com/atye/wikitable2json/files/14391766/json.txt)

**Comment by atye** [comment]
@KevinAnthony 

I've merged the fixes into master. If you have further questions about this, feel free to re-open or open a new issue.

**Comment by KevinAnthony** [comment]
thank you.

This fixed my problem!
